### PR TITLE
Fixed the Navbar bug, where the dark-light theme switching doesnt work as expected. 

### LINKED ISSUE #1510: Theme change toggle issue (Nav Bar)
Screenshot 2024-07-28 212651
Screenshot 2024-07-28 212637

Havving an issue of toggling theme modes in navBar

### PR DESCRIPTION
**Pull request by Sourabh782**
## Description
Fixed the Navbar bug, where the dark-light theme switching doesnt work as expected. 
I have attached video samples of each change briefing the ORIGINAL navbar working and mine Corrected working for your reference.

## Related Issues
There were bugs in navbar of every page in toggling dark-light mode, I fixed the toggling bus in every page's navbar and now the navbars of each page are working fine as expected
I have myself tested the theme change working of navbars at every page.

Pages that i have worked on includes : 
Home page
Contact Us Page
Menu Page
Service Page
Rate Us Page
Offers Page
Login Page
Sign Up Page
My Cart Page

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #1510 

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

1. Bug in contact us page Navbar:
https://github.com/user-attachments/assets/ace3741d-6224-4180-939d-92abdf41afa9

resolved:
https://github.com/user-attachments/assets/4fbe3f55-5408-44f5-9f22-74eb2ceafe20

2. Bug in Langing page Navbar:
https://github.com/user-attachments/assets/29b39dba-c362-4003-806f-4f8616f63edd

resolved:
https://github.com/user-attachments/assets/8a00cbf5-bc69-4c1d-aacd-8324745d714a

3. Bug in Menu page Navebar:
https://github.com/user-attachments/assets/f60b3c6f-f6b0-4095-a0aa-86330ab96d2c

resolved:
https://github.com/user-attachments/assets/bc7f5262-8ef9-4788-968c-5be3e71b2c8f

4. Bug in Service page Navbar:
https://github.com/user-attachments/assets/3947fccd-17a4-4472-8fe1-17e430e94f67

resolved:
https://github.com/user-attachments/assets/021f5c15-aa49-41f8-a6ff-865d31bf488c

5. bug in Rate Us Page Navbar:
https://github.com/user-attachments/assets/62ad8473-d873-4c50-a6a3-786ea3398b3e

resolved:
https://github.com/user-attachments/assets/89e3527c-e33e-4570-9cff-4f70a4ef2fa5

6. Bug in Offers page Navbar:
https://github.com/user-attachments/assets/483f0287-6ee7-40a4-a5d4-0d9bb31dc138

resolved:
https://github.com/user-attachments/assets/b8215800-d7e3-40ee-bd7c-bb173625bd25

7. Bug in  Login Page Navbar
  resolved:
https://github.com/user-attachments/assets/a3f9dec1-46df-43ee-90f4-db5dc8d1ad3f

8. Bug in Mycart navbar:
resolved:
https://github.com/user-attachments/assets/cb0ad620-7c95-4390-b871-6f906ceabf2f

9. Bug in signup page navbar:
resolved:
https://github.com/user-attachments/assets/48088fb0-c4b5-4693-b120-8fcec50633fc

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]
I have also changed the sun logo representing the day toggle option, As previous logo was not visible and created confusion.

Thanks for Assigning this issue to me, Hope for good results 👍

### CODE REVIEW

**Comment by Sourabh782** [comment]
@sunny0625 can u add relevant level tag?

**Comment by Sourabh782** [comment]
can you check it @khushi-joshi-05 ?

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by Sourabh782** [comment]
@sunny0625  Resolved conflicts, kindly check

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by Sourabh782** [comment]
Hello @sunny0625, I will add new pr for this issue, it was generating unknown errors

**Comment by Sourabh782** [comment]
@sunny0625, I have added a new PR #1601, which has no conflict. please check it 
Screenshot 2024-08-09 095712

**Pull request closed without merging**
