### PR TITLE
Add effect

### PR DESCRIPTION
**Pull request by Nikuunj**
# Description

Add a mouse effect when moving the mouse. The effect should be rendered effect like a render small food icons.
fix the company logo it is not link.

Fixes:  #652 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Nikuunj** [comment]
@khushi-joshi-05  @sunny0625

**Comment by sunny0625** [comment]
check your changes in 😎 Deploy Preview navbar Spoiled and both logo showing in the menu webpage.

**Comment by sunny0625** [comment]
image

**Comment by Nikuunj** [comment]
@khushi-joshi-05 @sunny0625

**Pull request merged**
