### PR TITLE
update footer section of services and properly linked css of offer section

### LINKED ISSUE #1006: BUG : Improper Footer of Services section and missing Css of offer section
1. Footer of services section is not proper. Check the attached image . 

Screenshot 2024-06-07 011147

2. Css of offer section is not linked properly in the repository .

Screenshot 2024-06-07 012354

### PR DESCRIPTION
**Pull request by ANKeshri**
fixes #1006 

I have fixed the issue and updated the footer of services section . 
Screenshot 2024-06-07 011147

I have linked the css of offer section properly .
Screenshot 2024-06-07 012354

### CODE REVIEW

**Comment by ANKeshri** [comment]
@khushi-joshi-05 @sunny0625 
I have fixed this issue and created a pull request for the same . Please assign this issue to me and merge my pull request under gssoc label .

**Comment by ANKeshri** [comment]
@khushi-joshi-05 please assign this issue to me and merge my pull request

**Comment by sunny0625** [comment]
Did you get assigned this issue #1006?

**Comment by ANKeshri** [comment]
> Did you get assigned this issue #1006?

please assign it to me @sunny0625

**Pull request closed without merging**
