### PR TITLE
Improvement in Navbar and Improve Offers section

### PR DESCRIPTION
**Pull request by KomalSrivastava**
## Description

I have Improved in Navbar . Previously it only show that tacky Red hove which was not looking good . i have add enhancement in it will share the screenrecording with you also so you can see . Also i have added effect of roll in button theme.
this fixes issue number #1368  #1371 
I have solved 2 issues here
## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

https://github.com/user-attachments/assets/e7cd0a1b-4a7b-435e-91b5-e4903a90e727

I have made changes in offer section as the color is to dark and the img is not good so i have changed that which 
Fixes issue number  #1371 
 i will share the screenshot with you :- 
Screenshot 2024-07-28 162106

@sunny0625 @khushi-joshi-05 Kindly review it and merge. Add GSSoC and level label in it. You can add Level 3 because  this Pull Request consist of  2 Issues. 

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by KomalSrivastava** [comment]
@khushi-joshi-05 Kindly review it and merge.

**Comment by KomalSrivastava** [comment]
@sunny0625 @khushi-joshi-05 I have 2 more issues who's Pull Request i have to merge . Please merge this ASAP

**Comment by khushi-joshi-05** [comment]
@KomalSrivastava the navbar icons are not visible in light mode

**Comment by khushi-joshi-05** [comment]
@KomalSrivastava solve conflicts

**Comment by KomalSrivastava** [comment]
@khushi-joshi-05 Solved

**Comment by KomalSrivastava** [comment]
@khushi-joshi-05 Solved

**Comment by KomalSrivastava** [comment]
@khushi-joshi-05 Solved , Kindly merge my Pull Request . I have 2 more issues to solve please merge this .

**Comment by KomalSrivastava** [comment]
@sunny0625 @khushi-joshi-05 Merge please its been 4 days??

**Comment by KomalSrivastava** [comment]
@sunny0625 @khushi-joshi-05 I have opened this  Pull Request from last week !!

**Comment by KomalSrivastava** [comment]
@sunny0625 @khushi-joshi-05 Merge please its been 6 days !! I have 2 more issues to complete before it ends please do this asap.. It's a request..
Add level label in it , please see i have done 2 issues here so add level 3.

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by KomalSrivastava** [comment]
@sunny0625 @khushi-joshi-05 Resolved..

**Pull request merged**
