### PR TITLE
Updated Contact Us Page. #14

### PR DESCRIPTION
**Pull request by Damini2004**
Following changes updated in the contact us section
1.Responsiveness to whole contact section will be achieve.
2.Add carousel to the menu items that make it more tempting.
3.Proper validation of field will be added into the contact section .
4.Card and hover effect for upcoming discount, collaborations, games and many more.
5.Social Media Integration via in the icon format.

Issue number : #14 

Kinldy go through it and add suitable label it will be more beneficial.
Screenshot 2024-05-26 021559
Screenshot 2024-05-26 021612

Video of the Contact us section.

https://github.com/khushi-joshi-05/Food-ordering-website/assets/119414762/30e1785e-be42-4781-9cdf-1b08d6bcb958

### CODE REVIEW

**Comment by khushi-joshi-05** [comment]
@Damini2004, can you make the following changes?

Change the nav-bar to make it similar to the other pages.
Change the footer to match the existing ones.

**Comment by Damini2004** [comment]
Sure mam
Any other changes ?
And can you add level label to this PR ?

**Comment by Damini2004** [comment]
@khushi-joshi-05  kindly go through the PR mam

**Comment by Damini2004** [comment]
@khushi-joshi-05 Is the conflict has been resolved ?

**Pull request closed without merging**
