### PR TITLE
FIx the Outdated Page Footer

### LINKED ISSUE #1433: Some Pages have Outdated Footers
Hey @sunny0625 and @khushi-joshi-05 

Footer is outdated In some pages

### **Footer in home page**

image

### **Footer in other pages**

image

please assign this issue to me!

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Description

Hey @khushi-joshi-05 and @sunny0625 

- issue fixes #1433

I have fix the footers in some pages with the newer one 
- menu
- contact
- nutrition
- offer
- services
- shray

image

https://github.com/user-attachments/assets/8582b4bc-abf7-4dcd-beed-8d538e997c37

## Type of PR

- [x] Bug fix
- [x] Feature enhancement

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@sunny0625 pls take a  look and review it, thank you!

**Comment by MastanSayyad** [comment]
Hey @sunny0625 @khushi-joshi-05 pls merge this PR

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by MastanSayyad** [comment]
@sunny0625 I have resolved the conflicts

**Pull request merged**
