### PR TITLE
Modified The Login and Sign-Up Pages

### PR DESCRIPTION
**Pull request by babasekhar**
Hai @khushi-joshi-05 

I Modified the Login and Sign-Up pages and attracted the before and after Images

### **Before**
**Login Page**
Screenshot 2024-06-08 174125
**Sign-Up Page**
Screenshot 2024-06-08 174136

### **After**
**Login Page**
image
**Sign-Up Page**
image
and I am requesting you to please add the level label so it so help full to me.....🥺

Thank you 
Baba Sekhar.

### CODE REVIEW

**Comment by sunny0625** [comment]
Mention issue!

**Comment by babasekhar** [comment]
Issue regarding about the UIUX of login and sign up page modified

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by babasekhar** [comment]
conflicts are resolved

**Pull request merged**
