### PR TITLE
Added forgot.html and forgot password is added in login.html

### PR DESCRIPTION
**Pull request by UdayaNarne**
Screenshot 2024-06-17 at 9 09 44 AM
Screenshot 2024-06-17 at 9 09 48 AM

### CODE REVIEW

**Comment by sunny0625** [comment]
Mention Your Issue..!

**Comment by UdayaNarne** [comment]
Forgot page was not added previously,I have added it and I have made a pull request

**Comment by khushi-joshi-05** [comment]
@UdayaNarne solve the conflicts.

**Comment by UdayaNarne** [comment]
Can you please tell me what conflicts I need to solve apart from adding forgot password page

**Review by UdayaNarne — COMMENTED** [review]
Reviewed the lines that I added in Css-files/login1.css and Html-files/login.html

**Review by UdayaNarne — COMMENTED** [review]
Reviewed all the files

**Pull request closed without merging**
