### PR TITLE
Footer payment links

### LINKED ISSUE #1061: [Feat] : Add Pages for Footer links
@khushi-joshi-05 
@sunny0625 

we can make seperate pages for footer
currently all pages redirect us to `#`

image

### PR DESCRIPTION
**Pull request by dhruv8433**
@sunny0625 

[Feat] : Add Pages for Footer links #1061

close #1061

## description

added footer payment component links and also when user click on that they will redirected to  `/payment/:option`

### CODE REVIEW

**Comment by dhruv8433** [comment]
@sunny0625 

kindly please check this and merge it

**Comment by dhruv8433** [comment]
@sunny0625

kindly please check this and merge it
so i can make another pr

**Comment by khushi-joshi-05** [comment]
@dhruv8433 can u describe this pr

**Comment by dhruv8433** [comment]
@khushi-joshi-05 
@sunny0625

kindly please check this and merge it
so i can make another pr

**Comment by dhruv8433** [comment]
@sunny0625 

Please add level

**Pull request merged**
