### PR TITLE
added logo

### PR DESCRIPTION
**Pull request by shivathmikavemula**
Hello PA
I had added logo
### Screenshot-
Screenshot (28)

### after
Screenshot (29)

### CODE REVIEW

**Comment by shivathmikavemula** [comment]
Issue no-1109
@khushi-joshi-05

**Comment by shivathmikavemula** [comment]
please assign the gssoc levels to it @khushi-joshi-05

**Comment by shivathmikavemula** [comment]
I had completed the task 
issue no: 1109
Please assign the gssoc levels @sunny0625

**Comment by sunny0625** [comment]
Did you get assigned this issue #1109?

**Pull request closed without merging**
