### PR TITLE
Added Forget Password section

### LINKED ISSUE #765: Adding Forget password section
There is no forget password option. I can add the section out there in sign in and sign up page. 

Please assign this task to me under GSSoC'24. Add relevant labels into this.

image

### PR DESCRIPTION
**Pull request by MuraliDharan7**
Forget password section is added in LOGIN page. Also new file was created forget password section and linked with login page.

- Closes #765 

## Screenshots:

1.
image

2.
image

### CODE REVIEW

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by MuraliDharan7** [comment]
> solve conflicts.

Solved. Kindly add levels into this

**Comment by sunny0625** [comment]
image

**Comment by MuraliDharan7** [comment]
from my side It is still getting the page. Can you briefly explain where the error occurs and where should I change?

**Comment by sunny0625** [comment]
image
getting this error

**Pull request merged**
