### PR TITLE
Fixed the menu link, service link, contact us link

### PR DESCRIPTION
**Pull request by Phil94comp**
I fixed the menu link, service link, contact us link, and the cart link in the footer of the home page to navigate to the page the user wants to visit.

### CODE REVIEW

**Comment by sunny0625** [comment]
Tag your Issue!

**Comment by Phil94comp** [comment]
The issue I am addressing in this pull request is issue #487 Menu link, service link, contact us link not working properly in footer section.

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by sunny0625** [comment]
And this is not an issue. The links are working fine!

**Pull request closed without merging**
