### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by siddhant-2002**
logo changed

### CODE REVIEW

**Comment by siddhant-2002** [comment]
hey please review my pr and merge it as soon as possible

**Comment by khushi-joshi-05** [comment]
@siddhant-2002  check it first. All icons in navbar are repeating

**Comment by siddhant-2002** [comment]
i am not getting what you are saying but I have created new icon and added it

**Comment by siddhant-2002** [comment]
image

**Comment by sunny0625** [comment]
Mention Your Issue ID..!

**Comment by siddhant-2002** [comment]
#965

**Comment by siddhant-2002** [comment]
Any updates?

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by siddhant-2002** [comment]
conflict ressolved @sunny0625

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by siddhant-2002** [comment]
hey @sunny0625  i am solving simillar conflicts again and again I guess other person is also working on my logo branch and making changes so conflicts is occurring please merge it as soon as possible so it will wont appear again

**Pull request merged**
