### PR TITLE
Added Cursor Trail Effect Matching to the Website Design Theme

### LINKED ISSUE #1529: Add Cursor Trail Effect Matching to the Website Design Theme
Hey @khushi-joshi-05 @sunny0625 

To enhance the visual appeal and user interaction on our website, we propose adding a cursor trail effect that is consistent with our existing design theme. 

like this

https://github.com/user-attachments/assets/9ae971b1-3291-4275-9c43-a2d9fa1bc2b1

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
## Description
Hey @khushi-joshi-05 @sunny0625 

- issue closes #1529 

I have added the trail effect, which is designed to match the website's theme, providing a visually appealing and cohesive user experience.

Changes Implemented
- A cursor trail effect that follows the mouse pointer was added.
-  Customized the trail effect to match the website's design theme, ensuring consistency with the overall look and feel.

https://github.com/user-attachments/assets/c8f79e94-aa7b-491e-8c37-7bacc15cca6f

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by RadhikaMalpani1702** [comment]
@sunny0625 @khushi-joshi-05 Please merge this PR

**Comment by RadhikaMalpani1702** [comment]
@sunny0625 @khushi-joshi-05 Please take a look at this PR

**Comment by RadhikaMalpani1702** [comment]
@sunny0625 and @khushi-joshi-05 Please merge this PR

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by RadhikaMalpani1702** [comment]
@sunny0625 I have solved the conflicts please merge this PR

**Comment by RadhikaMalpani1702** [comment]
@sunny0625 @khushi-joshi-05 Please merge this PR

**Pull request merged**
