### PR TITLE
Change the "foodies" logo on home page to the one on menu page.

### PR DESCRIPTION
**Pull request by Stevecmd**
I was able to complete one of the tasks:
- Change the "foodies" logo on home page to the one on menu page.

### CODE REVIEW

**Comment by sunny0625** [comment]
Mention issue!

**Comment by Stevecmd** [comment]
> * Change the "foodies" logo on home page to the one on menu page.

Hi, it was:
"Level 1 issues. #1052"

**Comment by sunny0625** [comment]
Did you get assigned this issue #1052?

**Comment by Stevecmd** [comment]
Sorry, seems I skipped the assignment bit.

**Pull request closed without merging**
