### PR TITLE
Improved the UI of Contact Us Page

### PR DESCRIPTION
**Pull request by jency1**
#585 Fixed

Please review and merge this PR.

@sunny0625 @khushi-joshi-05

### CODE REVIEW

**Comment by khushi-joshi-05** [comment]
@jency1 solve conflicts

**Comment by jency1** [comment]
> @jency1 solve conflicts

@khushi-joshi-05 Conflicts resolved.

Please review and merge this PR.

**Comment by jency1** [comment]
@khushi-joshi-05 @sunny0625 Conflicts resolved.

Please review and merge this PR.

**Comment by jency1** [comment]
@sunny0625   Can you change the level from level1 to level2 ? 

For login page UI also I was given level2 that's why I am telling. 

If it's possible then do change it. 

Thank you.

**Pull request merged**
