### PR TITLE
add a hover effect on menu counters

### PR DESCRIPTION
**Pull request by shuhaki**
add a hover effect on menu counters #641 

Screenshot 2024-06-02 at 12 54 36 AM

### CODE REVIEW

**Comment by sunny0625** [comment]
This PR can't be merged into the main.
Check your changes in 😎 Deploy Preview.

**Comment by sunny0625** [comment]
image
Your PR making this!

**Comment by shuhaki** [comment]
Screenshot 2024-06-10 at 12 49 01 AM

**Pull request closed without merging**
