### PR TITLE
Home page navigation

### PR DESCRIPTION
**Pull request by SHANMUGAPRIYA-1**
I had created a Home button in the log in page which has navigation functionality which allows the users to navigate to the home page directly from the existing page.

### CODE REVIEW

**Comment by SHANMUGAPRIYA-1** [comment]
Please do label the pull request

**Comment by sunny0625** [comment]
Mention Issue

**Comment by sunny0625** [comment]
Not working!
check on the Deploy preview.

**Comment by sunny0625** [comment]
image
change this path address this is your local system path.

**Pull request closed without merging**
