### PR TITLE
Enhance the Cart

### LINKED ISSUE #1124: enhance the cart
image
here img is not display as well as not align and lots of.

### PR DESCRIPTION
**Pull request by Varsani2520**
## Description

1.image url store 
2.fetch img
3.style the cart

## Related Issues

#1124
- Closes #1124

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
before:
image

after:
image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Varsani2520** [comment]
@sunny0625 ,review it and merged with with level

**Comment by Varsani2520** [comment]
@sunny0625 ,please merged it with level

**Comment by Varsani2520** [comment]
@khushi-joshi-05,please merged it and alos give the responsed 

if you dont give response then i complaint in gssoc 
if you merged this PR with level label then i solve next issue

**Comment by khushi-joshi-05** [comment]
@Varsani2520 Look we have to respond to many PRs and issues and responding to all at same time isn't possible so keep patience.

**Pull request merged**
