### PR TITLE
Improved Offers Page

### LINKED ISSUE #1526: Improve the offers page
i. Readability Issus 
image

ii. Improve slideshow UI
image

iii. Change the images

### PR DESCRIPTION
**Pull request by sau-mili**
## Description
- Added slideshow for top offers 
- Improved the other carousel slideshow
- Improved the readability of the cards on hover
-

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #1526

## Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-08-05 184745

Screenshot 2024-08-05 184722

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by sau-mili** [comment]
@sunny0625 Please check this before merging other commits on same files. My PR is older than the recent commits.

**Comment by sau-mili** [comment]
@sunny0625  I have resolved conflicts twice today, please check this

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by sau-mili** [comment]
solved please check. @sunny0625

**Pull request merged**
