### PR TITLE
Added visitors count

### LINKED ISSUE #1452: Addition of visitors count
A visitor counter keeps track of how often a website is accessed and typically displays the number of visitors at the bottom of the homepage. 

image

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#1452

## Description

A visitor counter keeps track of how often a website is accessed and typically displays the number of visitors at the bottom of the homepage.

Visitors count increaments as the the visitor visits the page

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #1452 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/4a300252-6088-4a76-8cf6-3c58b41b43fa

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@sunny0625 @khushi-joshi-05 please review the PR.

**Comment by Anjaliavv51** [comment]
@sunny0625 @khushi-joshi-05 please review the PR add add level label

**Comment by Anjaliavv51** [comment]
@sunny0625 @khushi-joshi-05 please review the PR add add level label

**Comment by sunny0625** [comment]
Direct PR is not allowed...!

**Comment by Anjaliavv51** [comment]
@sunny0625 can I create another PR.

**Comment by Anjaliavv51** [comment]
@sunny0625

**Pull request closed without merging**
