### PR TITLE
Adding a  Donate Button

### PR DESCRIPTION
**Pull request by sahithinandikula**
## Related Issue
This PR is about adding a donate option to the website #1020 

## Description
I have created a donate button which when clicked redirects to another page asking the donor to provide the details asked.

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [x] Other (specify): __Adding donate button__________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/41e996a1-f803-40f3-81f8-ef30534fbd5d

https://github.com/user-attachments/assets/8a00b99e-0e04-4f55-9f4d-7e5419726ad9

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by sunny0625** [comment]
Mention issue ID!

**Comment by sahithinandikula** [comment]
@sunny0625 it's #1020

**Comment by sahithinandikula** [comment]
@sunny0625 Kindly review this PR

**Comment by sahithinandikula** [comment]
@sunny0625 can you please approve this pull request and assign a label to this? Let me know if you have any problem regarding this pull request

**Comment by sahithinandikula** [comment]
@sunny0625 please merge this PR and assign a level label too, so that points are added to the leaderboard

**Comment by sahithinandikula** [comment]
@sunny0625 merge this pull request

**Pull request merged**
