### PR TITLE
added beautiful food discount page

### LINKED ISSUE #1235: [Feat] : Add Foodie Discount page
@khushi-joshi-05 
@sunny0625 

we can add beautiful page on `offers/food-discount.html`

something like this

image

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

@sunny0625 

[Feat] : Add Foodie Discount page #1235

close #1235

## Description
[Please include a brief description of the changes or features added]

- added `Food Discount` Page
- make it reponsive
- set layout as per website design

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

image

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@sunny0625 

kindly please check this and merge it
also add level

**Comment by dhruv8433** [comment]
@sunny0625

kindly please check this and merge it
also add level

**Comment by dhruv8433** [comment]
@sunny0625

kindly please check this and merge it
also add level

**Comment by dhruv8433** [comment]
@khushi-joshi-05 
@sunny0625

kindly please check this and merge it
also add level

**Comment by sunny0625** [comment]
where to navigate to your page?

**Comment by dhruv8433** [comment]
@sunny0625 

from footer click `Food Discount` option
image

**Comment by dhruv8433** [comment]
@sunny0625 

now you can check that and merge this

**Pull request merged**
