### PR TITLE
the cart footer and the items have been improved

### LINKED ISSUE #658: Cart Page UI improvement
image
The Ui of the cart section needs improvement 
please assign this issue to me  @khushi-joshi-05

### PR DESCRIPTION
**Pull request by Sypher0Dronzer**
Fixed #658 

## **Before**

image

image

## **After**

image

image

I have made the necessary changes as per the issue.

### CODE REVIEW

**Comment by sunny0625** [comment]
The issue has been resolved, Do one thing in this PR change the colour of text in cart webpage.

**Comment by sunny0625** [comment]
image

**Comment by Sypher0Dronzer** [comment]
okay

**Comment by Sypher0Dronzer** [comment]
image
The requested changes have been made

**Pull request merged**
