### PR TITLE
Made navbar sticky

### PR DESCRIPTION
**Pull request by Saimanjari777**
#701 fixed

I have made the navbar sticky in home, menu, services, and contact us pages

Screenshot 2024-05-31 210503
Screenshot 2024-05-31 210551
Screenshot 2024-05-31 210405
Screenshot 2024-05-31 210421

### CODE REVIEW

**Comment by sunny0625** [comment]
image
On some pages, there is getting problem.

**Comment by Saimanjari777** [comment]
I have made the changes, Please check once @sunny0625 
Screenshot 2024-05-31 221846

**Comment by sunny0625** [comment]
image

In the menu and service page, the nav bar goes out.

**Comment by Saimanjari777** [comment]
I have made the changes, now the navbar doesn't go out. Please check once @sunny0625

**Pull request merged**
