### PR TITLE
menu page inserted 

### PR DESCRIPTION
**Pull request by kairveeehh**
#16  issue 16 resolved , created a decent menu page with hover effects to resolve the error page loading issue 
## @khushi-joshi-05  please review and merge it its been done since 4 days already

### CODE REVIEW

**Comment by khushi-joshi-05** [comment]
@kairveeehh a menu page is already there

**Comment by kairveeehh** [comment]
> @kairveeehh a menu page is already there
> 

@khushi-joshi-05 but it was assigned to me by you only

**Comment by kairveeehh** [comment]
> > @kairveeehh a menu page is already there
> > 
> 
> @khushi-joshi-05 but it was assigned to me by you only

And also I have done the work 4 days before itself

**Comment by kairveeehh** [comment]
> > > @kairveeehh a menu page is already there
> > > 
> > 
> > @khushi-joshi-05 but it was assigned to me by you only
> 
> And also I have done the work 4 days before itself

@khushi-joshi-05  what should I do now??

**Comment by khushi-joshi-05** [comment]
@kairveeehh can u attach the screenshot of menu page created by you.
Menu page was already there but it wasn't linked.

**Comment by kairveeehh** [comment]
@khushi-joshi-05  here it is , I had worked on it 3 day before and my PR was also raised but the later ones got merged first so..
Screenshot 2024-05-14 151746

**Comment by kairveeehh** [comment]
> @kairveeehh it is really nice. can u just update its navbar and starting part like this Screenshot 2024-05-14 152330
> 
> And also link the add to cart and price section to javascript. Go through the existing files and in the about section a link is also attested, so you can check the working . If you can make these changes then surely i will merge it. Make sure it is working.

@khushi-joshi-05  ok I will try my best to achieve it

**Comment by kairveeehh** [comment]
@khushi-joshi-05  can u please label the PR as according to the announcements it is necessary

**Comment by kairveeehh** [comment]
@khushi-joshi-05 can you please attach labels , it wont be counted elsewise , please do it 
@khushi-joshi-05

**Pull request merged**
