### PR TITLE
Added the preloader

### LINKED ISSUE #827: add a preloader
adding a preloader engages the user while the page is loading

### PR DESCRIPTION
**Pull request by samarsajad**
## Description
Created a preloader that is displayed for 3s
## Screenshot

https://github.com/khushi-joshi-05/Food-ordering-website/assets/142666229/25c1d3ef-ca98-4fb7-ab48-873f9c8ba175

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @khushi-joshi-05 @sunny0625

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by samarsajad** [comment]
> solve conflicts.

Done. Kindly take a look @sunny0625

**Comment by sunny0625** [comment]
see your changes in 😎 Deploy Preview.

**Comment by samarsajad** [comment]
> see your changes in 😎 Deploy Preview.

I checked the changes in deploy preview. It is working as expected. lemme know if you want changes or something @sunny0625

**Comment by sunny0625** [comment]
PreLoader is Working Fine after that see the Website!

**Comment by sunny0625** [comment]
Level will given by @khushi-joshi-05

**Comment by samarsajad** [comment]
please assign level to this pull request . My contributions won't be counted otherwise @sunny0625

**Pull request merged**
