### PR TITLE
Added hover for containers

### LINKED ISSUE #992: Image Error and hover- Offers Page
## Description
There is an image error with loading image in the Offers page. The path has not mentioned properly or added properly.
Also there is no hover effect with it. I want to fix both the issues.
This need to be fixed.

Please assign this to me under GSSoC'24.

add relevant labels into this issue.
## Screenshots:
image

### PR DESCRIPTION
**Pull request by MuraliDharan7**
## Description 
1. Added hover for image, and made the offers container creative by adding other effects.

2. Made the collaboration container as same as others.

- Closes #992 

## Screenshots:

Before: 
1.
image
2.
image

After:
1. 
image

2. 
image

### CODE REVIEW

**Comment by sunny0625** [comment]
image
see your changes in 😎 Deploy Preview.

**Comment by MuraliDharan7** [comment]
Kindly check it now

**Comment by sunny0625** [comment]
> Kindly check it now

image
see your changes in 😎 Deploy Preview.

**Comment by MuraliDharan7** [comment]
Can you check now? 
If it still get the same, please guide me through solving this, if possible.

**Pull request merged**
