### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by ughsurbhi**
I have edited the buttons and made it look more appealing. Thank you.

### CODE REVIEW

**Comment by sunny0625** [comment]
Mention your issue!

**Comment by sunny0625** [comment]
Describe properly!

**Comment by sunny0625** [comment]
Show some screenshots of your changes..!

**Comment by sunny0625** [comment]
Where the issue you have create mention or I will close this PR.

**Comment by ughsurbhi** [comment]
at line 704

**Comment by sunny0625** [comment]
> at line 704

Tag Issue ID.

**Comment by ughsurbhi** [comment]
it is not showing in the issue section but as far as i remember it was like "sticky footer". one of its label was 'level1' .
[ughsurbhi](https://github.com/ughsurbhi) wants to merge 1 commit into [khushi-joshi-05:main](https://github.com/khushi-joshi-05/Food-ordering-website/tree/main) from [ughsurbhi:patch-1](https://github.com/ughsurbhi/Food-ordering-website/tree/patch-1)

**Pull request closed without merging**
