### PR TITLE
Search bar added

### PR DESCRIPTION
**Pull request by Riyasharma28**
An animated search bar has been added right now it's now working because the navigation to other web pages is not being done, I would request you kindly review it, if any changes are required let me know, and I'll do it!
I would request to merge these pull requests  #339 #368 #356  for better User Friendly UI

### CODE REVIEW

**Comment by sunny0625** [comment]
add some preview of changes.

**Comment by sunny0625** [comment]
solve conflicts and preview the changes

**Comment by sunny0625** [comment]
@Riyasharma28

**Comment by Riyasharma28** [comment]
hey sir!
sorry for the delay i had my exams going on, kindly check once it's working from my side if it still not works let me know ill modify more

**Pull request closed without merging**
