### PR TITLE
Restyled the footer component

### LINKED ISSUE #1535: Styling the footer
image

Items are not aligned and some of them are not properly positioned
I will also add proper hover effects

### PR DESCRIPTION
**Pull request by ayush-848**
## Description
Enhanced the footer
Fixed alignment and added hover effects

## Related Issues

- Closes #1535

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
https://www.awesomescreenshot.com/video/30174601?key=9627e347160c0cbf0470b066b3651eb8

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by ayush-848** [comment]
@khushi-joshi-05 please check it

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by ayush-848** [comment]
@sunny0625 check now

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by ayush-848** [comment]
> solve conflicts.

@sunny0625 check now

**Pull request merged**
