### PR TITLE
Fixed Duplicate contact us links

### PR DESCRIPTION
**Pull request by jency1**
## Related Issue
#515 - Fixed two contact us links in navbar in home page.

Please review and merge this PR.

@sunny0625 @khushi-joshi-05

## Description
Duplicate contact us pages leads to misunderstanding and makes user feel uncomfortable to use the website. Hence it needs to  be resolved as soon as possible, so I have resolved the duplicate links.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Before : 
Screenshot 2024-07-08 202635

After : 
Screenshot 2024-07-08 202645

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jency1** [comment]
@sunny0625 Please review and merge this PR. I have solved the issue.

**Comment by khushi-joshi-05** [comment]
@jency1 still there are two icons .kindly recheck

**Comment by jency1** [comment]
> @jency1 still there are two icons .kindly recheck

@khushi-joshi-05 I have resolved this issue. Please review it again and merge this PR.

Thank you.

**Comment by jency1** [comment]
@sunny0625 Please add the level label.

**Comment by jency1** [comment]
@sunny0625 @khushi-joshi-05  Please add the level label and merge this PR.

**Comment by jency1** [comment]
@sunny0625 @khushi-joshi-05 I have resolved all the issues. Please add the level label and merge this PR as soon as possible.

**Pull request merged**
