### PR TITLE
Page not found(services.html) - Issue resolved 

### PR DESCRIPTION
**Pull request by samyakmaitre**
When navigating to the offers web page from the service page showing "Page Not Found"

As per your mail, I have found and resolved issue for "Page not found". Kindly accept my PR and assign gssoc labels.
Thank you!

### CODE REVIEW

**Comment by sunny0625** [comment]
Mention Issue!

**Comment by samyakmaitre** [comment]
> Mention Issue!

When navigating to the offers web page from the service page showing "Page Not Found"

As per your mail, I have found and resolved issue for "Page not found".

**Comment by sunny0625** [comment]
You can't make Direct PR..!

**Review by khushi-joshi-05 — COMMENTED** [review]
redundant files

**Pull request merged**
