### PR TITLE
Fixed Hover effects for the site Issue

### PR DESCRIPTION
**Pull request by kamalesh-og**
Hello Project Admin,
Fixed Issue Number - #15 

**Pull Request:** Resolve Issue #15  - Hover effects for the site.

**Description:**
This pull request adds hover effects for all components on the webpage, excluding the footer. Additionally, it refactors the CSS code to improve readability and maintain consistency.

**Changes Made:**
- Added hover effects for cards in the menu and about_us sections, and for all buttons.
- Refactored CSS code for better organization and readability.

**Screenshots:**
image
Added Hover for Order Now button
image
Added Hovering Transitions to the About Us card.
image
Added Hover for Order Online, Take Out Order, Book table Buttons.
image
Added Hover for View All Buttons.
image
Added Hovering Transitions to the Menu Items card.
image
Added Hover for Google Play Store and  Apple Store Buttons.

**Checklist:**

- [x] Added hover effects for all components on the webpage including all the buttons and the cards(menu and about_us).
- [x] Refactored CSS code to improve readability.
- [x] Tested the changes locally and ensured proper functionality.

**Reviewer:**
@khushi-joshi-05 

**Reviewer Checklist:**

- [ ]  Verified that hover effects are consistent and visually appealing.
- [ ] Checked CSS changes for proper organization and readability.
- [ ] Ensured the changes function correctly across different devices.

Please review the changes and let me know if any further modifications are required.

### CODE REVIEW

**Comment by kamalesh-og** [comment]
Hi @khushi-joshi-05,
Can you suggest an idea for this issue because i resolved the issue given by adding the hover effects
but still, it is showing conflicts why though?

**Comment by kamalesh-og** [comment]
Hi @khushi-joshi-05 , 
Can you merge this PR, I resolved the issue of Conflict merge
Thank You.

**Comment by sunny0625** [comment]
solve conflicts

**Comment by kamalesh-og** [comment]
Thank you @sunny0625 for contributing to this repo

**Pull request merged**
