### PR TITLE
Added more dishes in Goat Categories

### PR DESCRIPTION
**Pull request by SadafKausar2025**
fixed issue : #1152 

Screenshot (2024)

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @sunny0625 
can you please review this PR and merge it

**Comment by AmbitiousCoder-07** [comment]
Really sorry to interrupt @SadafKausar2025 but I think you're trying to add static meal data to the dynamically rendered data. This way you'll be changing the meals data for every meal category instead of just goat type and that way, you'll also be displaying 18 meals per page with repeated entries. The approach works fine for goat page as the API data contains only one dish for that category, however it would ruin the layout for others. 
I suggest you create two separate meals and add that to the rendered meals data only for the goats category using some conditional statement. OR You could just try adding the data statically to the html file itself!

**Comment by sunny0625** [comment]
image

This PR have issue!

**Comment by SadafKausar2025** [comment]
> image
> 
> This PR have issue!

ok I will fix it

**Pull request closed without merging**
