### PR TITLE
Added Icons to Footer

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Added Icons to Footer Links - Solved #1539 
Kindly go through this PR @sunny0625 

kk

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@sunny0625 kindly please go through this PR and add level label under GSSOC'24

**Comment by sailaja-adapa** [comment]
@sunny0625 kindly please go through this PR and add level label under GSSOC'24

**Comment by sailaja-adapa** [comment]
@sunny0625 kindly please go through this PR and add level label under GSSOC'24

**Comment by sailaja-adapa** [comment]
@sunny0625 kindly please go through this PR and add level label under GSSOC'24

**Comment by sailaja-adapa** [comment]
@sunny0625 kindly please go through this PR and add level label under GSSOC'24

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by sailaja-adapa** [comment]
I solved conflicts please go through it @sunny0625

**Pull request merged**
