### PR TITLE
Adding Header page & Footer page in Signup.html

### PR DESCRIPTION
**Pull request by Ravindrak0812**
Adding Header page  & Footer page  in Signup.html 
#1102

### CODE REVIEW

**Comment by sunny0625** [comment]
Did you get assigned this issue #1103?

**Comment by Ravindrak0812** [comment]
> Did you get assigned this issue #1103?

No I find this issue and  i fix it.

**Comment by Ravindrak0812** [comment]
Merge my pull request.

**Comment by Ravindrak0812** [comment]
can you merge my pull request

**Comment by Ravindrak0812** [comment]
Merge my PR  and update my leaderboard
@khushi-joshi-05/Food-ordering-website
***@***.***>

**Comment by Ravindrak0812** [comment]
generate level 1 Lable for this issue @sunny0625

**Comment by Ravindrak0812** [comment]
merge my pullrequest @sunny0625 @khushi-joshi-05

**Pull request closed without merging**
