### PR TITLE
more sections added with cards

### PR DESCRIPTION
**Pull request by Ansh101112**
## Description
This PR resolves issue #298 

## Screenshots
Screenshot (77)

## Note
This PR is under GSSOC'24

### CODE REVIEW

**Comment by Ansh101112** [comment]
@sunny0625 sir please see this PR as it resolves the issue as it resolves the issue #298 and also please assign and add gssoc badge and level to this.

**Comment by Ansh101112** [comment]
@khushi-joshi-05 ma'am please see

**Comment by khushi-joshi-05** [comment]
@Ansh101112 u have done good job but  a menu page already exists there.
You can find some other issue.

**Comment by Ansh101112** [comment]
> @Ansh101112 u have done good job but  a menu page already exists there.
> You can find some other issue.

Ma'am I resolved the issue and add new branch of dish and cards in it

**Comment by khushi-joshi-05** [comment]
@Ansh101112 I didn't read it properly.

I have merged it.

**Comment by Ansh101112** [comment]
> @Ansh101112 I didn't read it properly.
> 
> I have merged it.

Thank you ma'am

**Comment by Ansh101112** [comment]
@khushi-joshi-05 ma'am please close the issue #298

**Comment by Ansh101112** [comment]
@khushi-joshi-05 @sunny0625 please assign me on this merged pr.

**Pull request merged**
