### PR TITLE
contact page ready

### PR DESCRIPTION
**Pull request by bhumika-1127**
I have solved the error of navbar where the links to other pages were not opening. Apart from that I have created a contact page for your website.

### CODE REVIEW

**Comment by khushi-joshi-05** [comment]
@bhumika-1127 since there is a change in overall file structure your branch is showing conflicts. Can u resolve it.

**Comment by bhumika-1127** [comment]
i have added the contact us page and also there were some issues with the links of the navbar inside the html-files folder. Also the issue with view menu button is solved.

**Comment by bhumika-1127** [comment]
Thank You @khushi-joshi-05 for merging. Kindly add a label of GSSOC'24.

**Comment by khushi-joshi-05** [comment]
@bhumika-1127 can u format the footer and make its design similar to other pages.

**Comment by bhumika-1127** [comment]
I have made the required change @khushi-joshi-05. As this branch is merged and the pull request is closed, I have created a new pull request with the updated changes #221 . You can accept the request from here #221 . Don't forget to add GSSOC label to that request too.

**Comment by bhumika-1127** [comment]
@khushi-joshi-05 Kindly add label for levels too, as it will be used for evaluating the score.

**Pull request merged**
