### PR TITLE
Fixed footer section for mobile screen size

### LINKED ISSUE #917: fix footer for MOBILE screen
the footer is not proper sized for the mobile screen 
it should be fixed to improve the user experience on all devices.

image

I would love to contribute to his project.

### PR DESCRIPTION
**Pull request by Utsavladia**
## Description
Fixed the footer section to be responsive on all screen sizes
[Please include a brief description of the changes or features added]

## Related Issues
#917 
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #917 

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Utsavladia** [comment]
@sunny0625 
should i resolve the conflicts to get this PR merged

**Comment by khushi-joshi-05** [comment]
@Utsavladia yes u will have to resolve conflicts

**Comment by Utsavladia** [comment]
@khushi-joshi-05 
Resolved ✅

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by Utsavladia** [comment]
@sunny0625 
Resolved again ✅

**Pull request merged**
