### PR TITLE
update UI of contact us page  

### PR DESCRIPTION
**Pull request by Tarungupta18**
#360 
### Update the UI of ContactUpdate.html page make it responsive

Screenshot (52)

Screenshot (53)

**I have made a responsive UI of the contact us page its look very nice just good fit with other pages like home , services page.**

### CODE REVIEW

**Comment by Tarungupta18** [comment]
please merge this branch

**Comment by Tarungupta18** [comment]
@sunny0625 please review my PR

**Comment by sunny0625** [comment]
Solve Conflicts

**Comment by Tarungupta18** [comment]
Okay I will solve conflict

**Comment by Tarungupta18** [comment]
Please also assign level

**Comment by Tarungupta18** [comment]
please approve my PR

**Comment by sunny0625** [comment]
Which Issue do you get assigned?

**Comment by sunny0625** [comment]
It is unfair for other Contributors who are making Direct PR not allowed..!

**Comment by sunny0625** [comment]
#360 Already closed as the assigned contributor's PR is merged..!

**Pull request closed without merging**
