### PR TITLE
added beautifully desgin culinary experience page

### LINKED ISSUE #1241: [Feat] : Add Personalized Culinary Experiences page
@sunny0625 

we can add `/offers/culinary-experience.html` for Footer Exclusive Offers component

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

@khushi-joshi-05 

[Feat] : Add Personalized Culinary Experiences page #1241

close #1241

## Description
[Please include a brief description of the changes or features added]

- added beautiful Personalized Culinary Experiences page
- add some styling
- make it responsive

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

image

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@khushi-joshi-05 

kindly review this and inform me if you need any modifications

**Comment by dhruv8433** [comment]
@khushi-joshi-05

kindly review this and inform me if you need any modifications

**Comment by dhruv8433** [comment]
@khushi-joshi-05

kindly review this and inform me if you need any modifications

**Comment by dhruv8433** [comment]
@khushi-joshi-05

kindly review this and inform me if you need any modifications

**Comment by dhruv8433** [comment]
@sunny0625 

Kindly please check this and merge it
And add level

**Comment by dhruv8433** [comment]
@sunny0625

Kindly please check this and merge it
And add level

**Comment by sunny0625** [comment]
> @sunny0625
> 
> Kindly please check this and merge it And add level

Tag @khushi-joshi-05, not me!

**Comment by dhruv8433** [comment]
@khushi-joshi-05 

kindly please check this and merge it

**Comment by dhruv8433** [comment]
@khushi-joshi-05 

kindly please response
check this and merge it

**Comment by dhruv8433** [comment]
@khushi-joshi-05 

Please add level

**Comment by dhruv8433** [comment]
@khushi-joshi-05 

Kindly please add level 
I completed whole page

**Comment by dhruv8433** [comment]
@sunny0625 

please add level

**Pull request merged**
