### PR TITLE
navbar updated

### PR DESCRIPTION
**Pull request by siddhant-2002**
spacing and gap cleared

hover effect added

enhanced arrangement

### CODE REVIEW

**Comment by siddhant-2002** [comment]
hey review my pr and merge it as soon as possible

**Comment by sunny0625** [comment]
Mention Your Issue ID?

**Comment by siddhant-2002** [comment]
#966

**Comment by siddhant-2002** [comment]
Any updates?

**Comment by sunny0625** [comment]
see your changes in 😎 Deploy Preview.

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by siddhant-2002** [comment]
@sunny0625 i have corrected it before also I guess someone also try to work on branch navbar and conflicts happens everytime if you merge it as soon as possible I think it would wont happpen

**Pull request merged**
