### PR TITLE
enhance contact-form 

### LINKED ISSUE #1244: wish to enhance the contact us form
Screenshot 2024-07-01 210239

this is the sample for contact us form

### PR DESCRIPTION
**Pull request by ankita685**
fixes #1244

### CODE REVIEW

**Comment by sunny0625** [comment]
Did you get assigned this issue #1244?

**Comment by ankita685** [comment]
> Did you get assigned this issue #1244?

no

**Comment by ankita685** [comment]
> Did you get assigned this issue #1244?

will  you merge it or not?

**Comment by ankita685** [comment]
@sunny0625 why u labelled it as invalid?

**Comment by sunny0625** [comment]
> @sunny0625 why u labelled it as invalid?

!!..No Direct PR Allowed..!!

**Comment by ankita685** [comment]
> > @sunny0625 why u labelled it as invalid?
> 
> ### No Direct PR Allowed!

can you assign me this issue?

**Pull request closed without merging**
