### PR TITLE
enhancement: Want to display No. of items of cart icon #690

### PR DESCRIPTION
**Pull request by nishant0708**
-Added CartCount icon fully Functioning 

Screenshot 2024-06-04 033933

### CODE REVIEW

**Comment by nishant0708** [comment]
Yes I can actually I saw that issue but I think someone might be working on it so i doesn't make changes. Should I solve it?

**Comment by sunny0625** [comment]
Mention Issue!

**Comment by nishant0708** [comment]
There was no issue such like that so i have raised that issue i will fix that #928

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by nishant0708** [comment]
@sunny0625 please check it now

**Pull request closed without merging**
