### PR TITLE
Updated Footer On Services Module #871

### PR DESCRIPTION
**Pull request by thenagarajanv**
3 Issues Cleared Please Check it out @khushi-joshi-05 and Please Label it as gssoc  and level 2. Loved to Work on this Project and thanks for having it on Open-Source

1. Updated Service Module Footer Styles

Before
old 2 1

After
new 2 1

2. Background Image Fixed On Contact Module

Before
old 1 1

After
new 1 1

3. Cursor Changed On Navigation Bar section for Login 

Before
old 3 1

After
new 3 1

### CODE REVIEW

**Comment by sunny0625** [comment]
Mention Your Issue!

**Comment by thenagarajanv** [comment]
Added Issue, Please Check it @sunny0625 #897

**Comment by sunny0625** [comment]
Direct PR is invalid.

**Comment by sunny0625** [comment]
@khushi-joshi-05 check for this PR.

**Pull request closed without merging**
