### PR TITLE
Beautify the Navbar with animated icons

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Related Issue #1267
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/khushi-joshi-05/Food-ordering-website/assets/137484958/0d66151a-9399-4da2-af0a-2979f7ab37e6

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @khushi-joshi-05  and @sunny0625 
please review this PR and merge it

**Comment by SadafKausar2025** [comment]
hello @sunny0625 
please merge it

**Comment by SadafKausar2025** [comment]
I have resolved the conflict

**Comment by SadafKausar2025** [comment]
Hello @sunny0625 please merge my pr

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by SadafKausar2025** [comment]
> solve conflicts.

@sunny0625 
yes done resolving conflict
please merge it

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by SadafKausar2025** [comment]
> solve conflicts.

yes solving

**Pull request merged**
