### PR TITLE
Fixed the services box issue #1396 

### PR DESCRIPTION
**Pull request by gollaanusha249**
I made the text in the services box to visible 

image

### CODE REVIEW

**Comment by sunny0625** [comment]
Mention issue ID..!

**Comment by gollaanusha249** [comment]
Issue ID - #1396

**Comment by gollaanusha249** [comment]
@khushi-joshi-05 kindly review this PR and assign labels(level)

**Comment by sunny0625** [comment]
Direct PR is not allowed..!

**Comment by gollaanusha249** [comment]
@khushi-joshi-05 Then please assign me the isuue id #1396

**Pull request closed without merging**
