### PR TITLE
Upgraded Contact Us UI

### PR DESCRIPTION
**Pull request by SakiraAli1115**
Hello PA,
Here is the updated UI of the Contact Page.

- Issue #483

### Screenshot -
image

### - kindly merge this PR.

### CODE REVIEW

**Comment by sunny0625** [comment]
first Pull the Previous changes in the main branch.
Menu effect is not applied in your PR.

**Comment by sunny0625** [comment]
Solve conflicts I will merge into the main.

**Comment by SakiraAli1115** [comment]
Hello @sunny0625 ,
Kindly review the PR now.

**Comment by sunny0625** [comment]
@khushi-joshi-05 gtg?

**Comment by Tarungupta18** [comment]
@sunny0625 
please assign me this issue

**Pull request closed without merging**
