### PR TITLE
Included chatbot feature

### PR DESCRIPTION
**Pull request by AditiPrabhakar**
Resolved issue #592

Included chatbot feature, if provided, I can add logo to the icon too.

if any more changes are required, or if there is any bug please let me know.

I can add location, timings, customer care and other specifications if you want.

### CODE REVIEW

**Comment by sunny0625** [comment]
Mention issue!

**Comment by sunny0625** [comment]
Solve conflicts

**Comment by sunny0625** [comment]
comment the previous chatbot.
As it creates an overlap issue!

**Comment by AditiPrabhakar** [comment]
> comment the previous chatbot. As it creates an overlap issue!

I'm sorry, but I think I have already done that, can you please check again?

**Comment by sunny0625** [comment]
@AditiPrabhakar can you provide a screenshot of your changes?
As in 😎 Deploy Preview, the issue of overlap is not solved.

**Comment by AditiPrabhakar** [comment]
Screenshot (113)
Screenshot (112)


Can you please guide me a bit, i'm actually new to open source.

**Comment by sunny0625** [comment]
@AditiPrabhakar I've Analysed your code.
- Could you do one thing comment the code from line no. 606 - 618.
- Also your chatbot is Hiding under NavBar.
- In CSS try to give the height and weight of your chatbot according to a better view.

**Pull request merged**
