### PR TITLE
theme added

### LINKED ISSUE #1125: dark theme is not working
when i click on dark button then dark theme not applied
image

apply theme ,
in whole website
step1 :choose theme 
step 2: make theme file where add background,text color ,card color in light and dark theme
step 3:wrapped theme in app file
step 4:store theme in storage
step 5:apply theme in all file

### PR DESCRIPTION
**Pull request by Varsani2520**
## Description

i fixed theming issue 

## Related Issues

#1125
- Closes #1125

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist

- [ ] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have performed a self-review of my code
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Varsani2520** [comment]
@khushi-joshi-05 ,now merged it

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by Varsani2520** [comment]
@khushi-joshi-05 ,i solve the conflicts ,now please merged it

**Comment by Varsani2520** [comment]
@khushi-joshi-05 ,please merged it

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by Varsani2520** [comment]
@khushi-joshi-05 please merged it

**Comment by Varsani2520** [comment]
@khushi-joshi-05 ,please merged it with level label

**Pull request merged**
