### PR TITLE
Register button added at login page

### PR DESCRIPTION
**Pull request by mehrun171**
### Register Button Added at Login Page
issue number: #872 resolved
The feature was to add Register Button at Login Page
Successfully added the Register button.

Check these screenshots:

Before:

Screenshot 2024-06-03 131530

After:

Screenshot 2024-06-11 231147

I have checked the code Thoroughly and this don't generate any new errors and the code is neat and clean.
I'm a GSSOC contributor and do let me know for any further changes...
do checkout the PR

### CODE REVIEW

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by mehrun171** [comment]
Solved

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by sunny0625** [comment]
see your changes in 😎 Deploy Preview.

**Comment by sunny0625** [comment]
https://github.com/khushi-joshi-05/Food-ordering-website/assets/76521579/093e6e6b-0827-4aa4-855f-e64c7d1bf89b

**Comment by sunny0625** [comment]
> I didn't get u...there are no conflicts na..so what's the problem?

Did you see the video clip I sent earlier the problem is if I merge this PR, the Login Page will show like this. Did you understand?

**Comment by sunny0625** [comment]
@khushi-joshi-05 will check this PR!

**Comment by mehrun171** [comment]
@sunny0625 Actually the changes i made do not look like this...i have already attached screenshots in pr...please check them

**Pull request closed without merging**
