### PR TITLE
#1053 solved

### PR DESCRIPTION
**Pull request by Vikashchou-dhary**
As per the mention issue and correction needed I have made changes in the services page
services page

services page 1

services page 2

### CODE REVIEW

**Comment by sunny0625** [comment]
@khushi-joshi-05 will check this PR.

**Comment by Vikashchou-dhary** [comment]
@khushi-joshi-05  please review the PR

**Comment by sunny0625** [comment]
Mention Issue ID?

**Comment by sunny0625** [comment]
#1053

**Comment by Vikashchou-dhary** [comment]
i have solved the conflicts please check it

**Pull request closed without merging**
