### PR TITLE
Membership page

### LINKED ISSUE #1238: [Feat] : Add Membership page
@sunny0625 

we can add `offers/membership.html` for footer Exclusive Offers page

### PR DESCRIPTION
**Pull request by dhruv8433**
## Description

@sunny0625 

[Feat] : Add Membership page #1238

close  #1238

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #1238

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@sunny0625 

please check this and merge it

**Comment by dhruv8433** [comment]
@khushi-joshi-05 
@sunny0625 

please check this and merge it

**Comment by khushi-joshi-05** [comment]
@dhruv8433 this page is not connected to home!?

**Comment by dhruv8433** [comment]
@khushi-joshi-05 

yes, it is connected to home
click on `membership benifits` from footer

image

**Comment by dhruv8433** [comment]
@khushi-joshi-05 

please check this and merge it

**Comment by sanjay-kv** [comment]
image
 these points are against guidelines, will be reducing scores from other repos as i dont have access to the same

**Comment by dhruv8433** [comment]
@sanjay-kv 

please add atleast level 2 or 1

**Pull request merged**
