### PR TITLE
Added Vip food event

### LINKED ISSUE #1565: [Feat] : Add Vip Food Event Page
@sunny0625 

we can add new route for vip food event page

image

please assign me i would like to work on this

### PR DESCRIPTION
**Pull request by dhruv8433**
## Description

@sunny0625 

[Feat] : Add Vip Food Event Page #1565

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #1565

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

image

image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@sunny0625 

please check this and merge it

**Comment by dhruv8433** [comment]
to check output click on vip food event in index.html

image

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by dhruv8433** [comment]
@sunny0625 

now you can merge this

**Comment by dhruv8433** [comment]
please sir check this and merge it

**Pull request merged**
