### PR TITLE
placed search bar in the webpage

### PR DESCRIPTION
**Pull request by kesava23**
Fixed Issue #189

### CODE REVIEW

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by kesava23** [comment]
conflicts are clear now .

**Comment by kesava23** [comment]
no conflicts with the base branch

**Comment by kesava23** [comment]
no conflicts with the base branch, conflicts are clear @sunny0625

**Comment by kesava23** [comment]
no conflicts with the base branch

**Pull request merged**
