### PR TITLE
Added the Marquee Effect

### PR DESCRIPTION
**Pull request by suraj-9849**
issue : #11 
I Have added the best marquee effect and with this marquee the user can be updated faster so that he should not wait for the single text to come so I have Replicated the text and added the best animations to it and also changed the font-family to Poppin which gives the premium look. @sunny0625 @khushi-joshi-05

### CODE REVIEW

**Comment by sunny0625** [comment]
give preview of the changes you made?

**Comment by suraj-9849** [comment]
May I know how to show the preview @suraj-9849

**Comment by sunny0625** [comment]
Show the ss of the changes you made.

**Comment by sunny0625** [comment]
solve conflicts

**Comment by suraj-9849** [comment]
https://github.com/khushi-joshi-05/Food-ordering-website/assets/146669517/127b4748-45dd-4866-96d5-dc5310a07aca

**Comment by suraj-9849** [comment]
Screenshot 2024-05-19 185235

**Comment by suraj-9849** [comment]
Please add the GSSOC label here also it is not considered in the leader board
@sunny0625

**Pull request merged**
