### PR TITLE
Added Hover Effects on Footer Links and Buttons, Added Logos of Playstore and Appstore

### PR DESCRIPTION
**Pull request by kushagrakiyawat**
**Fixes**
Fixes issue #12 

**Description**
Added a hovering effect on the links. Added pointer cursor to the buttons and links. Added class 'social-links" to the social media icons, "footer-links" to the links in the footer and "btn" for buttons. Also added the Playstore and App Store icons from font-awesome. 

**Screenshots**

image

The pointer is not visible in the screenshot, but the effect is.

**Checks**
I have checked it on localhost and it working properly

### CODE REVIEW

**Comment by sunny0625** [comment]
@kushagrakiyawat solve conflicts
@khushi-joshi-05 should we need the logo in the button?

**Comment by sunny0625** [comment]
Preview changes and solve conflicts

**Comment by sunny0625** [comment]
Close this PR and see hover effect is only on the landing page.
Do these things in New PR:
- Add a footer Social media icon hover effect on every web page.
- Improve the footer Social media icon on other pages like on the Menu and Service page.

**Comment by sunny0625** [comment]
@kushagrakiyawat

**Comment by kushagrakiyawat** [comment]
ok @sunny0625

**Pull request closed without merging**
