### PR TITLE
Enhance navbar

### LINKED ISSUE #1113: enhance navbar
the navbar looks really basic . planning to enhance it and make it stylish

### PR DESCRIPTION
**Pull request by sanayamahajan-23**
## Description

[Please include a brief description of the changes or features added]
enhanced navbar added neon light effect and also made the logo image on home path correct. in menu corrected the path of the services and home 

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #1113

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by khushi-joshi-05** [comment]
@sanayamahajan-23 solve the conflicts

**Comment by sanayamahajan-23** [comment]
resolved conflicts

**Comment by khushi-joshi-05** [comment]
@sanayamahajan-23 i think neon coloured bg is not matching with the websites theme. Check if any other color suits otherwise remove this effect.

**Comment by sanayamahajan-23** [comment]
@khushi-joshi-05 changed the color now it looks harmonic

**Comment by khushi-joshi-05** [comment]
still showing conflicts

**Comment by sanayamahajan-23** [comment]
Resolved them

**Comment by khushi-joshi-05** [comment]
image
@sanayamahajan-23

**Comment by sanayamahajan-23** [comment]
Resolved conflicts @khushi-joshi-05

**Comment by sanayamahajan-23** [comment]
@khushi-joshi-05  maam please merge the pr since my score is at stake

**Pull request merged**
