### PR TITLE
Book catering

### LINKED ISSUE #1447: Adding BookCatering
Adding BookCatering which allows user to book catering for required events.

image

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#1447

## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #1447 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/601c8974-6bf2-4ff6-bd73-47ade1fc2d80

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@khushi-joshi-05 please review the PR add level label assign me this PR , and also GSSOC label.

**Comment by Anjaliavv51** [comment]
https://github.com/user-attachments/assets/aea8abe1-e03e-445d-b15c-318865916bea

@sunny0625  @khushi-joshi-05 the above review is from the netifly

**Comment by Anjaliavv51** [comment]
@sunny0625 @khushi-joshi-05

**Comment by Anjaliavv51** [comment]
@sunny0625 @khushi-joshi-05 please review the PR add add level label

**Comment by Anjaliavv51** [comment]
@sunny0625 @khushi-joshi-05 please review the PR add add level label

**Comment by sunny0625** [comment]
Direct PR is not allowed..!

**Comment by Anjaliavv51** [comment]
@sunny0625 can I create another PR.

**Pull request closed without merging**
