### PR TITLE
added logo to the foodie navbar

### PR DESCRIPTION
**Pull request by jayanththalla**
in the navbar, I added the logo and made the cursor pointer
thank you for allowing me to contribute to your repository❤️
please label gssoc and level

### CODE REVIEW

**Comment by sunny0625** [comment]
Mention issue.

**Comment by sunny0625** [comment]
remove or comment the previous logo.

**Comment by jayanththalla** [comment]
fixes #665 
please add label gssoc and the level @pa

**Comment by sunny0625** [comment]
image
See your changes.

**Comment by jayanththalla** [comment]
> image See your changes.

this one not

**Comment by sunny0625** [comment]
@khushi-joshi-05 will review this PR.

**Pull request closed without merging**
