### PR TITLE
Would like to add preloader , custom and scroll bar?

### PR DESCRIPTION
**Pull request by Anjaliavv51**
issue #774

Add Custom Cursor to all the HTML pages

image

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@sunny0625 please review the PR

**Comment by Anjaliavv51** [comment]
@sunny0625 please review the PR

**Comment by Anjaliavv51** [comment]
@sunny0625  please review the changes

**Comment by Anjaliavv51** [comment]
@sunny0625 i add the cursor to all 16 files , if possible , please add Level 3 label

**Comment by Anjaliavv51** [comment]
@sunny0625 please review the changes

**Comment by sunny0625** [comment]
See your changes in 😎 Deploy Preview only preloader is loading

**Comment by Anjaliavv51** [comment]
https://github.com/khushi-joshi-05/Food-ordering-website/assets/154777864/25982550-5e3f-4038-a044-feb824da8e62


@sunny0625 please check I added the custom cursor pointer

**Comment by sunny0625** [comment]
image
not loading after this.

**Comment by Anjaliavv51** [comment]
@sunny0625 i will change the code

**Comment by Anjaliavv51** [comment]
@sunny0625  please review now.

**Comment by Anjaliavv51** [comment]
@sunny0625 please preview the changes now

**Comment by Anjaliavv51** [comment]
@sunny0625 please preview the changes now

**Comment by Anjaliavv51** [comment]
@sunny0625 please preview the changes now

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by Anjaliavv51** [comment]
@sunny0625 please check conflicts are resolved.

**Comment by Anjaliavv51** [comment]
@sunny0625 please check conflicts are resolved.

**Comment by Anjaliavv51** [comment]
@sunny0625 please review the changes

**Comment by Anjaliavv51** [comment]
@sunny0625 please review the changes

**Comment by Anjaliavv51** [comment]
@sunny0625 please review the PR

**Comment by Anjaliavv51** [comment]
@sunny0625 please review the PR.

**Comment by sunny0625** [comment]
solve conflicts.

**Pull request closed without merging**
