### PR TITLE
 Added "Scroll Down Progress Bar" Across All Pages

### LINKED ISSUE #1133: ✨ Add "Scroll Down Progress Bar"
### Feature Description

Hey @khushi-joshi-05  and @sunny0625  

I would like to suggest adding a scroll down progress bar to the website to enhance user experience. 

### Use Case

- A scroll progress bar visually indicates how much of the page has been scrolled and how much is left, providing users with a better sense of their position on the page. 
- This feature can be especially helpful for long pages blogs, docs, and articles.

### Benefits

- Enhances user experience by providing visual feedback.
- Useful for long pages or articles.
- Improves overall navigation and user satisfaction
- Looks more engaging.

### Add ScreenShots

like this

image

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Related Issue
Issue closes #1133

## Description

Hey @sunny0625 and @khushi-joshi-05 

I have added the **scroll-down progress bar** across all the pages of the website

image

https://github.com/khushi-joshi-05/Food-ordering-website/assets/101971980/38d1026a-99b3-47c5-b6a0-3c144718d0c7

## Type of PR

- [x] Feature enhancement

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@sunny0625 You can merge this PR, even if the deployment has failed the changes will work fine!!
if doesn't work then revert it back! Thank YOU!!

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by MastanSayyad** [comment]
@sunny0625 I have resolved the conflicts

**Comment by MastanSayyad** [comment]
@sunny0625 Could you please Merge This PR? also please add the Levels

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by MastanSayyad** [comment]
> @sunny0625 I have resolved the conflicts


@sunny0625 I have resolved the conflicts

**Pull request merged**
