### PR TITLE
Fixed Hover Color Matching in Navbar and Enhanced Navbar on Home Page

### PR DESCRIPTION
**Pull request by jency1**
## Related Issue
#411 - Solved Hover Color Matching in Navbar and Enhanced Navbar on Home Page

Please review and merge this PR.

@sunny0625 @khushi-joshi-05

## Description

Earlier, In Navbar on hovering the links, it matches the background color, so I solved that.

Also enhanced the navbar with proper spacing, removing duplications, color of the text, size and giving transition effect in the links.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Before : 
Screenshot 2024-07-08 210846

After : 
Screenshot 2024-07-08 210935

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jency1** [comment]
@sunny0625 Please review and merge this PR. I have solved the issue.

**Comment by sunny0625** [comment]
image
Solve this..!
see your changes in 😎 Deploy Preview.

**Comment by jency1** [comment]
> image Solve this..! see your changes in 😎 Deploy Preview.

@sunny0625 Thanks for informing to see the changes in Deploy Preview.

Now, I have resolved all the issues, Do check it and merge this PR.

**Comment by jency1** [comment]
@sunny0625 

Now, I have resolved all the issues, Do check it and merge this PR.

**Comment by jency1** [comment]
@sunny0625 @khushi-joshi-05 I have resolved all the issues, Please Do check it and merge this PR as soon as possible. Also add the level label. 

Thank you.

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by jency1** [comment]
> solve conflicts.

@sunny0625 I have resolved the conflict issue. Do check it once and merge this PR by adding the level labels. 

Thank you.

**Comment by jency1** [comment]
@sunny0625 I have resolved the conflict issue. Do check it once and merge this PR by adding the level label.

**Comment by jency1** [comment]
@sunny0625 I have resolved the conflict issue. Do check it once and merge this PR.

**Comment by sunny0625** [comment]
image
@khushi-joshi-05 @jency1

**Comment by sunny0625** [comment]
solve conflicts.

**Comment by jency1** [comment]
@sunny0625 I have resolved all the conflict issues. I have Removed all the duplicate links in navbar and enhanced the navbar.

Do check it and merge this PR as soon as possible along with the labels.

Here is the attached screenshot for your reference.

Screenshot 2024-07-20 204458

**Comment by jency1** [comment]
> @sunny0625 I have resolved all the conflict issues. I have Removed all the duplicate links in navbar and enhanced the navbar.
> 
> Do check it and merge this PR as soon as possible along with the labels.
> 
> Here is the attached screenshot for your reference.
> 
> Screenshot 2024-07-20 204458

Please merge this PR. @sunny0625 @khushi-joshi-05

**Comment by jency1** [comment]
@sunny0625 @khushi-joshi-05  Please merge this PR as soon as possible. I have solved all the conflict issues 6-7 times.

**Pull request merged**
