### PR TITLE
added superscript to the cart button

### LINKED ISSUE #1090: #improving the cart button
I have added a superscript on the cart button which shows number of elements added to the cart.please assign me this issue under gssoc'24.
Screenshot 2024-06-15 182656
when clicked on add to cart button
Screenshot 2024-06-15 182734

### PR DESCRIPTION
**Pull request by nandani-goyal**
## Description
I have added a superscript near the cart icon which shows exact number of items in the cart currently. On reload it may get 0 but when item is selected it again starts the counting from the current number of items in the cart. Like below when there was already one item in the cart the counting started from 1.

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #1090 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-07-23 210939
currently there is one item in the cart
Screenshot 2024-07-23 211838
when I added more items to it the number in the subscript changes as foolows:
https://github.com/user-attachments/assets/d1f34a66-9516-4a59-b59d-1a4556bfe276

## Checklist

- [ ] I have gone through the [contributing guide](https://github.com/khushi-joshi-05/Food-ordering-website/)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have performed a self-review of my code
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by khushi-joshi-05** [comment]
@nandani-goyal solve conflicts

**Comment by nandani-goyal** [comment]
@khushi-joshi-05  resolved👍.kindly check.

**Comment by nandani-goyal** [comment]
Kindly merge the pull request and there is a humble request of considering
this pull request of level 2.

**Comment by nandani-goyal** [comment]
@sunny0625 kindly merge this pr.

**Pull request merged**
