### PR TITLE
updated index.html

### PR DESCRIPTION
**Pull request by kanishk-2**
pull req id #971 and issue id #696 .
This is another pr bcz of workflow error

### CODE REVIEW

**Comment by kanishk-2** [comment]
add the gssoc tag and level tag.

**Comment by sunny0625** [comment]
Why creating 2 PR for 1 Issue?

**Comment by kanishk-2** [comment]
> Why create 2 PR for 1 Issue?

bcz there was some workflow error in the previous one this one is latest and correct one

**Comment by sunny0625** [comment]
Close one or combine them in one.

**Comment by kanishk-2** [comment]
> Close one or combine them in one.

closed pr #971

**Pull request merged**
